### ISSUE TITLE
The brand color

### ISSUE THREAD

**Issue by DutchPete** [Spekulucius/obsidian-adrenaline#1]
How does one get that red brand color? When I switch to Adrenaline I just get some purple. If it depends on setting the accent color, then what is the hex code for it?

**Comment by Spekulucius** [comment]
It was created with a hue color shift effect. Try #F55C7D :)

**Comment by DutchPete** [comment]
There are no style settings with this theme so where should I apply that hex code?

**Comment by DutchPete** [comment]
So, where do I put #F55C7D since there are no Style settings?

**Comment by Spekulucius** [comment]
I apologize for the late reply - adrenaline uses the same core-code as brainhack, so it uses the accent color to adjust its colors. I hope that helped!

**Comment by DutchPete** [comment]
Thank you.
